import PublicPageLayout, { InfoSection } from '../components/PublicPageLayout.jsx'

export default function Privacy() {
  return <PublicPageLayout eyebrow="Your information" title="Privacy Policy" intro="This policy explains what personal data Tenth Ki Padhai collects, why we use it and the choices available to students and parents.">
    <p className="text-sm text-ink/55">Effective date: 1 September 2026</p>
    <InfoSection title="1. Who is responsible"><p>Tracksoft Solutions Private Limited operates Tenth Ki Padhai and is responsible for personal data handled through the service. Privacy requests can be sent to <a className="underline" href="mailto:contact@tenthkipadhai.online">contact@tenthkipadhai.online</a>.</p></InfoSection>
    <InfoSection title="2. Data we collect"><ul className="list-disc pl-5 space-y-2"><li>Account and profile information, such as name, email, phone, school and study details supplied during registration.</li><li>Optional parent or guardian name and email.</li><li>Schedules, completed activities, quiz and test attempts, answers, scores and reports.</li><li>Package, order and payment-reference information. Complete card details, banking credentials and UPI PINs are handled by the payment provider and are not stored by us.</li><li>Device, login, security, audit and basic technical information needed to operate and protect the service.</li><li>Messages and information submitted through our contact form or customer-care channels.</li></ul></InfoSection>
    <InfoSection title="3. How we use data"><p>We use personal data to create and secure accounts; provide personalised schedules, content, tests and reports; administer packages and payments; send service, progress and parent notifications; respond to support enquiries; prevent misuse; maintain audit records; improve the service; and comply with law.</p></InfoSection>
    <InfoSection title="4. Data sharing"><p><strong>We do not sell or rent personal data, and we do not share it with advertisers.</strong> We disclose only the information necessary to trusted service providers that operate the platform on our behalf, such as Supabase for authentication and database services, Vercel for hosting, Razorpay for payments and Resend for email delivery. These providers process data for the relevant service under their own security and privacy obligations.</p><p>We may also disclose data if required by law, to protect users or the service, or in connection with a lawful corporate restructuring. We do not otherwise share student data with third parties.</p></InfoSection>
    <InfoSection title="5. Students under 18"><p>Tenth Ki Padhai is intended for school students, many of whom are minors. A student under 18 must obtain permission from a parent or legal guardian before registering. Parents or guardians may contact us to ask about, correct or request deletion of a minor’s personal data, subject to identity verification and legal retention requirements.</p></InfoSection>
    <InfoSection title="6. Retention and deletion"><p>We retain information while an account or package is active and afterwards only for as long as reasonably needed for support, security, academic history, legal compliance and dispute resolution. You may request account or personal-data deletion by emailing us with the subject “Privacy Request”. Some transaction, audit or legal records may need to be retained as required by law.</p></InfoSection>
    <InfoSection title="7. Security"><p>We use reasonable technical and organisational safeguards, access controls and authentication measures. No online service can guarantee absolute security. Keep your password private and notify us promptly if you suspect unauthorised access.</p></InfoSection>
    <InfoSection title="8. Your choices and rights"><p>You may ask to access, correct or delete personal data, withdraw consent where applicable, or raise a grievance by contacting us. We may verify your identity before acting on a request. Withdrawing necessary data may make it impossible to continue providing some services.</p></InfoSection>
    <InfoSection title="9. Cookies and service storage"><p>We use essential browser storage and similar technologies to keep users signed in, remember necessary preferences, secure sessions and operate the application. We do not use this data to sell profiles to advertisers.</p></InfoSection>
    <InfoSection title="10. Updates and contact"><p>We may update this policy as the service or law changes. Material updates will be notified through the application or registered contact details. Contact us at <a className="underline" href="mailto:contact@tenthkipadhai.online">contact@tenthkipadhai.online</a>, +91 96041 88725 or +91 96041 88726.</p></InfoSection>
  </PublicPageLayout>
}
