import PublicPageLayout, { InfoSection } from '../components/PublicPageLayout.jsx'

export default function Terms() {
  return <PublicPageLayout eyebrow="Legal" title="Terms and Conditions" intro="These terms govern your use of Tenth Ki Padhai. Please read them before creating an account or purchasing a package.">
    <p className="text-sm text-ink/55">Effective date: 1 September 2026</p>
    <InfoSection title="1. About the service"><p>Tenth Ki Padhai is a CBSE Class 10 study-planning and educational-content service operated by Tracksoft Solutions Private Limited (“we”, “us” or “our”). It provides schedules, summaries, notes, quizzes, tests, worksheets and progress reports. It supplements classroom learning and is not affiliated with or endorsed by CBSE.</p></InfoSection>
    <InfoSection title="2. Eligibility and guardian permission"><p>Students under 18 may use the service only with permission from a parent or legal guardian. By registering, a student confirms that this permission has been obtained. The parent or guardian is responsible for reviewing these terms and supervising the minor’s use of the service.</p></InfoSection>
    <InfoSection title="3. Accounts"><p>You must provide accurate information, keep login credentials confidential and tell us promptly about suspected unauthorised access. You are responsible for activity performed through your account. Accounts may not be sold, transferred or shared outside the registered student’s household.</p></InfoSection>
    <InfoSection title="4. Packages, access and payments"><p>Available packages, prices, feature limits and expiry dates are displayed before purchase. Paid packages are one-time purchases for the stated academic year and do not renew automatically. Free-trial duration and usage allowances may be configured by us. Package expiry is based on the displayed expiry date, irrespective of purchase date.</p><p>Payments are processed by Razorpay. We do not receive or store complete card, UPI PIN or banking credentials. A successful payment confirmation is required before paid access is activated. Upgrade availability and usage quotas are governed by the package shown at purchase.</p></InfoSection>
    <InfoSection title="5. Acceptable use"><p>You may use the service and its content for personal, non-commercial study. You must not copy or redistribute substantial content, resell access, scrape the service, defeat security or usage controls, upload malicious material, impersonate another person, or use the service unlawfully.</p></InfoSection>
    <InfoSection title="6. Educational content and results"><p>We work to keep content useful and accurate, but do not guarantee that it is error-free, complete, continuously available, or sufficient for any particular examination result. Scores and reports are learning aids and not official academic records. Students should verify important material with prescribed textbooks, teachers and official CBSE sources.</p></InfoSection>
    <InfoSection title="7. Intellectual property"><p>The platform, branding, software, original learning material and arrangement of content belong to us or our licensors. We grant each active student a limited, personal, non-exclusive, non-transferable and revocable right to use available content during their package term.</p></InfoSection>
    <InfoSection title="8. Suspension and changes"><p>We may suspend or terminate access for misuse, security risk, non-payment or material breach of these terms. We may maintain, improve or change the service and its content. Material changes to these terms will be communicated through the service or registered contact details and apply prospectively, except where immediate changes are required by law or security needs.</p></InfoSection>
    <InfoSection title="9. Liability"><p>To the extent permitted by law, we are not liable for indirect or consequential loss, loss arising from reliance on educational outcomes, connectivity failures, or circumstances beyond our reasonable control. Nothing in these terms excludes rights or liabilities that cannot lawfully be excluded, including applicable consumer rights.</p></InfoSection>
    <InfoSection title="10. Governing law and contact"><p>These terms are governed by Indian law. Subject to applicable consumer remedies, courts in Pune, Maharashtra have exclusive jurisdiction. Questions or grievances may be sent to <a className="underline" href="mailto:contact@tenthkipadhai.online">contact@tenthkipadhai.online</a> or raised through our Contact Us page.</p></InfoSection>
  </PublicPageLayout>
}
