import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase.js'
import { PageTitle } from './AdminSubjects.jsx'

export default function AdminCoupons() {
  const [coupons, setCoupons] = useState([]); const [message, setMessage] = useState(''); const [draft, setDraft] = useState({ code: '', discount_type: 'percentage', discount_value: '', usage_type: 'multiple', expires_at: '' })
  const load = async () => { const { data, error } = await supabase.from('coupons').select('*').order('created_at', { ascending: false }); if (error) setMessage(error.message); else setCoupons(data || []) }
  useEffect(() => { load() }, [])
  async function create(event) { event.preventDefault(); setMessage(''); const { error } = await supabase.from('coupons').insert({ ...draft, code: draft.code.trim().toUpperCase(), discount_value: Number(draft.discount_value), expires_at: new Date(draft.expires_at).toISOString() }); if (error) setMessage(error.message); else { setMessage('Coupon created.'); setDraft({ code: '', discount_type: 'percentage', discount_value: '', usage_type: 'multiple', expires_at: '' }); load() } }
  async function toggle(coupon) { const { error } = await supabase.from('coupons').update({ active: !coupon.active }).eq('id', coupon.id); if (error) setMessage(error.message); else load() }
  return <div><PageTitle eyebrow="Configuration manager" title="Coupons" text="Create, review and manually expire discount codes." />{message && <div className="card p-3 mb-4 bg-sky/20">{message}</div>}<form onSubmit={create} className="card p-5 mb-5 grid sm:grid-cols-5 gap-3"><input required className="form-control" placeholder="CODE" value={draft.code} onChange={e => setDraft({ ...draft, code: e.target.value.toUpperCase() })} /><select className="form-control" value={draft.discount_type} onChange={e => setDraft({ ...draft, discount_type: e.target.value })}><option value="percentage">Percent</option><option value="fixed">Fixed ₹</option></select><input required min="1" type="number" className="form-control" placeholder="Discount" value={draft.discount_value} onChange={e => setDraft({ ...draft, discount_value: e.target.value })} /><select className="form-control" value={draft.usage_type} onChange={e => setDraft({ ...draft, usage_type: e.target.value })}><option value="multiple">Multiple use</option><option value="one_time">One time</option></select><input required type="datetime-local" className="form-control" value={draft.expires_at} onChange={e => setDraft({ ...draft, expires_at: e.target.value })} /><button className="btn-primary sm:col-span-5">Create coupon</button></form><div className="space-y-3">{coupons.map(c => <article className="card p-4 flex flex-wrap items-center gap-3" key={c.id}><strong className="font-mono text-lg">{c.code}</strong><span className="chip bg-sun/30">{c.discount_type === 'percentage' ? `${c.discount_value}%` : `₹${(c.discount_value / 100).toFixed(0)}`}</span><span className="chip bg-sky/20">{c.usage_type === 'one_time' ? 'One time' : 'Multiple use'}</span><span className={`chip ${c.active && new Date(c.expires_at) > new Date() ? 'bg-leaf/30' : 'bg-flame/20'}`}>{c.active && new Date(c.expires_at) > new Date() ? 'Active' : 'Expired'}</span><span className="text-sm text-ink/60 flex-1">Expires {new Date(c.expires_at).toLocaleString()}</span><button className="btn-secondary text-sm" onClick={() => toggle(c)}>{c.active ? 'Expire manually' : 'Reactivate'}</button></article>)}{!coupons.length && <div className="card p-5 text-center text-ink/60">No coupons created.</div>}</div></div>
}
